include:
  - infra.yml

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: article_manager_app
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./src:/usr/src/app/src