export const USER_TOKENS = {
  USER_SERVICE: Symbol('USER_SERVICE'),
  USER_REPOSITORIES: Symbol('USER_REPOSITORIES'),

  PENDING_USER_SERVICE: Symbol('PENDING_USER_SERVICE'),
  PENDING_USER_REPOSITORIES: Symbol('PENDING_USER_REPOSITORIES'),
};
